openapi: 3.0.0
info:
  title: junjoAPI
  version: '1.0'
  contact:
    name: Paulo Márquez Herrero
    url: pmarquezh.info
    email: me@pmarquezh.info
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'http://localhost:8100'
    description: Local
paths:
  /junjoAPI/1.0/sequences:
    post:
      summary: ''
      operationId: post-1.0-sequences
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
      description: Creates a new sequence in storage.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SequenceRec'
        description: SequenceRec with the initial data.
    parameters: []
  '/junjoAPI/1.0/sequences/{sequenceId}':
    parameters:
      - schema:
          type: string
        name: sequenceId
        in: path
        required: true
        description: Id of the sequence to operate on
    get:
      summary: sequences
      operationId: get-1.0-sequences
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SequenceRec'
        '404':
          description: Not Found
      description: Retrieves the SequenceRec identified by sequenceId
    delete:
      summary: ''
      operationId: delete-1.0-sequences-sequenceId
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      description: Deletes a record identified by sequenceId
    put:
      summary: ''
      operationId: put-1.0-sequences-sequenceId
      responses:
        '204':
          description: 'All OK, record updated (or created)'
        '400':
          description: 'Bad Request, wrong data supplied.'
      description: Updates a SequenceRec
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SequenceRec'
        description: Data to update the record identified by the parameter "sequenceId"
components:
  schemas:
    SequenceRec:
      title: SequenceRec
      type: object
      description: Keeps the stored state of a sequence.
      x-examples:
        Sequence already in use:
          id: 78ebab54-884d-11ec-a8a3-0242ac120002
          sequenceName: SKUs
          format: '{AA}-{NNNN}'
          currentNumericSequence: 149
          currentAlphaSequence: AD
          priorityType: numeric
        New Sequence:
          id: 78ebab52-884d-11ec-a8a3-0242ac120002
          sequenceName: SKUs
          format: '{AA}-{NNNN}'
          currentNumericSequence: 0
          currentAlphaSequence: AA
          priorityType: numeric
      properties:
        id:
          type: string
        sequenceName:
          type: string
        format:
          type: string
        currentNumericSequence:
          type: integer
        currentAlphaSequence:
          type: string
        priorityType:
          type: string
